### ISSUE TITLE
curl --compressed connection not closed

### ISSUE THREAD

**Issue by puggan** [philippelt/simple_proxy#2]
I have a curl request that works without compressing, but when adding `--compressed` to it, it deliver the content, and then keeps the connection open until it times out, at 2minutes on my setup.

**Comment by philippelt** [comment]
Hello,

sorry for the long delay. Thank you for signaling a bug.

This repo hasn't been maintained for 7 years now, I think a large refactoring would be required and I do not have enough time currently to do it.

I just let the code on line in case it could be helpful to someone needing such tool. May be there are more sophisticated tools available now for http tracing.
